// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfxp-DJv6rQe6kZIEL5sfOFhaimJCDhwY',
    appId: '1:619249321420:web:7bad6da3477823fda64969',
    messagingSenderId: '619249321420',
    projectId: 'easecortebaseversion-7100f',
    authDomain: 'easecortebaseversion-7100f.firebaseapp.com',
    storageBucket: 'easecortebaseversion-7100f.appspot.com',
    measurementId: 'G-SS1YKSEJS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAACKzetml2CZKLCfELpkaqy_0GHHW1lvc',
    appId: '1:619249321420:android:e5c4866e29d78671a64969',
    messagingSenderId: '619249321420',
    projectId: 'easecortebaseversion-7100f',
    storageBucket: 'easecortebaseversion-7100f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGZBNS7ttuNM45ETuuRFvuCottZdYOZLA',
    appId: '1:619249321420:ios:843731b401bda8a4a64969',
    messagingSenderId: '619249321420',
    projectId: 'easecortebaseversion-7100f',
    storageBucket: 'easecortebaseversion-7100f.appspot.com',
    iosBundleId: 'com.example.baseBarbearia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGZBNS7ttuNM45ETuuRFvuCottZdYOZLA',
    appId: '1:619249321420:ios:ee7c2aafedd8680ba64969',
    messagingSenderId: '619249321420',
    projectId: 'easecortebaseversion-7100f',
    storageBucket: 'easecortebaseversion-7100f.appspot.com',
    iosBundleId: 'com.example.baseBarbearia.RunnerTests',
  );
}
